### ISSUE TITLE
How do i run mcbash in daemon mode

### ISSUE THREAD

**Issue by doomwithdon** [dougy147/mcbash#13]
I know how to run it in interactive terminal, is there a way to run the command in daemon thread mode so that one need not have an open active terminal?

**Comment by dougy147** [comment]
There is no built-in daemon mode. 
The most natural and easiest way might be to use a terminal multiplexer like `tmux`, but there are [various other ways to run commands in the background](https://linuxize.com/post/how-to-run-linux-commands-in-background/).
