### ISSUE TITLE
Doesnt seem to work on the portals that use a 2nd directory in the address

### ISSUE THREAD

**Issue by ian10951** [dougy147/mcbash#2]
2nd gen portal panels tend to do this

http://tanmedia.watch:8880/magportal

The magportal directory is added as part of the stalker portal address. When this is added to mcbash it saves every mac tested as valid.

/usr/local/bin/mcbash: line 238: /root/.mcbash/valid_macs_tanmedia.watch8880/magportal: No such file or directory
[1] 00:1A:79:1B:BF:4D [VALID!]
/usr/local/bin/mcbash: line 238: /root/.mcbash/valid_macs_tanmedia.watch8880/magportal: No such file or directory
[2] 00:1A:79:A9:10:BF [VALID!]
/usr/local/bin/mcbash: line 238: /root/.mcbash/valid_macs_tanmedia.watch8880/magportal: No such file or directory

More and more IPTV servers are moving to the 2nd gen panels now and use another directory in the portal address so it would be great if this could be fixed. The above error occurs on every 2nd gen panel I've tested.

Works great on 1st gen portal panels though, although these are becoming fewer and fewer these days with all the better servers moving to the 2nd gen panels. Very little left worth having anymore really on the 1st gen panels.

**Comment by dougy147** [comment]
Thanks @ian10951, I've updated the code accordingly and it should work with 2nd gen panels.

**Comment by Karaoglan1980** [comment]
Hi, have tried a few times and only get expired as a result.  Can someone try this for me and see if it works for you?  http://de.caneriptv.com:8080 Thank you
