### ISSUE TITLE
getting following error

### ISSUE THREAD

**Issue by zalim1** [dougy147/mcbash#20]
mkdir -p /usr/local/bin
sh build.sh
+ CONF_DEST=${HOME}/.config/mcbash
+ ALT_CONF_DEST=/etc
+ [[ -d ./build ]]
build.sh: 10: build.sh: [[: not found
+ mkdir ./build
+ touch ./build/mcbash
+ echo #!/bin/bash
+ echo CONF_DEST="${HOME}/.config/mcbash"
+ echo ALT_CONF_DEST="/etc"
+ cat ./misc/colors.conf+ 
sed /^#!\/bin\/\(ba\)\?sh/d ; /^#.*/d
+ cat ./func/00_dependencies
+ sed /^#!\/bin\/\(ba\)\?sh/d ; /^#.*/d
+ cat ./func/01_args
+ sed /^#!\/bin\/\(ba\)\?sh/d ; /^#.*/d
+ cat ./func/02_config_file
+ sed /^#!\/bin\/\(ba\)\?sh/d ; /^#.*/d
+ cat ./func/03_destination_folder
+ sed /^#!\/bin\/\(ba\)\?sh/d ; /^#.*/d
+ cat ./func/04_dns
+ sed /^#!\/bin\/\(ba\)\?sh/d ; /^#.*/d
+ + cat ./func/05_checkpoint
sed /^#!\/bin\/\(ba\)\?sh/d ; /^#.*/d
+ cat ./func/06_interface
+ sed /^#!\/bin\/\(ba\)\?sh/d ; /^#.*/d
+ cat ./func/07_mac
+ sed /^#!\/bin\/\(ba\)\?sh/d ; /^#.*/d
+ cat ./func/08_interactive_mode
+ sed /^#!\/bin\/\(ba\)\?sh/d ; /^#.*/d
+ cat ./func/09_proxy
+ sed /^#!\/bin\/\(ba\)\?sh/d ; /^#.*/d
+ cat ./func/10_scan
+ sed /^#!\/bin\/\(ba\)\?sh/d ; /^#.*/d
+ cat ./func/11_user_agent
+ sed /^#!\/bin\/\(ba\)\?sh/d ; /^#.*/d
+ cat ./func/99_mcbash
+ sed /^#!\/bin\/\(ba\)\?sh/d ; /^#.*/d
build.sh: 34: build.sh: Syntax error: redirection unexpected
Makefile:13: recipe for target 'install' failed
make: *** [install] Error 2

**Comment by dougy147** [comment]
You can try replacing every occurrence of `[[` and `]]` by `[` and `]` in `build.sh`.

**Comment by zalim1** [comment]
working now, i had to change:
cat ./misc/infos.txt > /tmp/infos_tmp.txt
while read -r lines; do
    if [ "${lines}" == "" ]; then
        echo -e "\n" >> ./build/mcbash;
    fi;
    echo -e "# ${lines}" >> ./build/mcbash;
done < /tmp/infos_tmp.txt
rm /tmp/infos_tmp.txt

**Comment by zalim1** [comment]
thanks alot.
