### ISSUE TITLE
Saving Valid MAC addresses + suggestion

### ISSUE THREAD

**Issue by Mattias16-beep** [dougy147/mcbash#25]
Hello,

First of all, thank you so much for the bash script; it's incredibly helpful and well-crafted.

However, I've encountered an issue where the script doesn't seem to save any valid MAC addresses. The file /.mcbash, where I believe the valid MACs should be stored, appears to be empty, even though I've found some valid addresses.

Could you please advise on how to resolve this issue?

Additionally, is it possible to identify where the function responsible for saving the valid MAC addresses is located? I couldn’t find it in the script, and I’d like to add a Discord webhook integration to receive notifications when a valid MAC address is detected.

Thank you for your assistance!

**Comment by Mattias16-beep** [comment]
![image](https://github.com/user-attachments/assets/35a78a0f-be6d-4f50-863c-54d038608119)

Everything is working fine now ! Thanks you so much.

**Comment by dougy147** [comment]
Glad you made it work your way!
That's really cool 😎
