### ISSUE TITLE
Invalid DNS format

### ISSUE THREAD

**Issue by Twistee** [dougy147/mcbash#27]
Hey guys i get the error invalid dns format with EVERY URL i tried. 
This is my input/output: mcbash -u yesimes.oknirvana.club:8880 -w 1.5 -b 10 -d 3 -s 1500 -t 2
grep: repetition-operator operand invalid
ERROR: invalid DNS format.

Am i doing something wrong?

**Comment by dougy147** [comment]
Hi @Twistee,

Could you provide the output of `grep -V`  and `bash --version`?

You are doing nothing wrong, I suspect this is some kind of compatibility problem with `grep`.

`mcbash` has a built-in URL checker that needs `grep` with extended regexp support (`-E`).
As far as I know, it should work with recent versions (even BusyBox). 

As a shaky workaround, you could try replacing everything in the `inspect_dns()` function by something dummy like `echo "Bypassing DNS checking."`.

**Comment by Twistee** [comment]
> `bash --version`

Thank you for trying to help :)

These are my versions => 
➜  ~ grep -V
grep (BSD grep, GNU compatible) 2.6.0-FreeBSD
➜  ~ bash --version
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin24)
Copyright (C) 2007 Free Software Foundation, Inc.

putting dummy code into the function also did not resolve the error for what ever reason..

**Comment by dougy147** [comment]
Classic macOS' out-of-date packages :/, he are some workarounds:

* upgrading grep or installing ggrep/ripgrep or whatever up-to-date grep-like compatible aliased to `grep`
* modify the `inspect_dns()` function (this must work, see below)
* add an option to bypass url verification (I'll probably add that for mac users)
 
 
 <br>
 
 Modifying `inspect_dns()` to bypass URL checking must work. Here's how you can proceed:
* open the script `./bin/mcbash` from this repo in your editor
* replace the function (currently from line 222 to 250) by this:
* ```console
  inspect_dns() {
      echo "Bypassing URL verification."
  }
    ```

* launch the script `sh ./bin/mcbash`

if this does not work, I'll add a bypass option

**Comment by dougy147** [comment]
Glad it worked :) !

Modifying it in the func directory can work too if you then run `sh build.sh` (it rebuilds the script inside the `./bin/mcbash` folder).
