### ISSUE TITLE
missing proxy support

### ISSUE THREAD

**Issue by sbeimel** [dougy147/mcbash#6]
missing proxy support could u add it

**Comment by dougy147** [comment]
Thanks for your request. Proxy support has been added

**Comment by sbeimel** [comment]
Is it possible to Use a proxyfile like Proxy.txt 
It this file i would like to add 10 or 100 or …. Proxy. For Each mac test it will rotate one Proxy of this list. HTTP or socks5 Proxy Support would be great

**Comment by dougy147** [comment]
What you ask is doable without further changes to mcbash. Check this simple bash loop :

``` bash
file="your_proxy_list.txt"
while :; do
   while read -r line; do
       mcbash -u "your-own-dns.com"  --proxy "$line" -s 1 -np
   done < $file
done 
```
It will launch mcbash without asking for parameters (`-np`) to check just 1 MAC (`-s 1`) while looping through "your_proxy_list.txt" line by line, indefinitely, and of course using each current line as the proxy address (`--proxy "$line"). Feel free to tweak this according to your needs.

HTTP and SOCK5 are already supported.

**Comment by sbeimel** [comment]
Hi thanks for advise but it is not what i mean. With this it will scan only 1 mac with different proxy. I think a good feature of you tool is to check all mac or mac range with proxy list. so e.g. 00:01:blabla Proxy1  then 00:01:huhu proxy 2 etc. is this possible ?
