### ISSUE TITLE
Cloned on ubuntu Budgie but wont run

### ISSUE THREAD

**Issue by kalenderfamily** [dougy147/mcbash#9]
Sorry for opening issue but dont know how to ask....

I cloned and have mcbash dir in personal storage home/user/mcbash

in terminal I go to mcbash and then try to launch typing mcbash

It says command not found...

**Comment by kalenderfamily** [comment]
lenovo@lenovo-ThinkPad-T400:~$ cd mcbash
lenovo@lenovo-ThinkPad-T400:~/mcbash$ mcbash
mcbash: Befehl nicht gefunden.
lenovo@lenovo-ThinkPad-T400:~/mcbash$ cd bin
lenovo@lenovo-ThinkPad-T400:~/mcbash/bin$ mcbash
mcbash: Befehl nicht gefunden.
lenovo@lenovo-ThinkPad-T400:~/mcbash/bin$

**Comment by dougy147** [comment]
try `./mcbash` instead.

```bash
git clone https://github.com/dougy147/mcbash
cd mcbash
./bin/mcbash # or : sudo make install && mcbash
```

**Comment by kalenderfamily** [comment]
Thanks worked!

**Comment by kalenderfamily** [comment]
I tried to Set range in config and Set identical start/end mac to Check wether it runs properly but Script checks randomly other macs?
